# Generated by Django 3.2.9 on 2021-12-17 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParagraphsCorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('en_content', models.TextField()),
                ('vi_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SourcesCorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageName', models.TextField()),
                ('pageLink', models.URLField()),
                ('xpathGetDocLinks', models.TextField()),
                ('xpathGetTitle', models.TextField()),
                ('xpathGetEnContent', models.TextField()),
                ('xpathGetViContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SentencesCorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_sentence', models.TextField()),
                ('vi_sentence', models.TextField()),
                ('st_order', models.IntegerField()),
                ('paragraphscorpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elastic.paragraphscorpus')),
            ],
        ),
        migrations.AddField(
            model_name='paragraphscorpus',
            name='sourcescorpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elastic.sourcescorpus'),
        ),
    ]
