# Generated by Django 3.2.9 on 2021-12-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0002_sourcescorpus_pagequery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcescorpus',
            name='pageQuery',
            field=models.TextField(),
        ),
    ]
