# Generated by Django 4.0.1 on 2022-01-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0006_paragraphscorpus_link_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcescorpus',
            name='continueWord',
            field=models.TextField(blank=True),
        ),
    ]
